theme: jekyll-theme-minimal
title: Zane Jobe, PhD
description: Sedimentologist | Research Professor | Earth-Resource Data Scientist

![Zane Jobe](https://core.mines.edu/wp-content/uploads/sites/206/2019/04/zane-jobe.jpg){:class="img-responsive"}
